# About the MA{VR}X Lab {-}

The **M**ixed **A**ugmented **V**i**R**tual e**X**tended (Reality) Laboratory (referred to as the MAVRX Lab, pronounced _mavericks_, and stylized with curly brackets around {VR}) is space in which we drive innovation through alternative reality modalities and research. It came about in early 2021 as an entity, though its physical location had existed for some time. MA\{VR\}X Lab is intended as a collaborate effort, meant to be interdisciplinary and reside in a place of praxis and innovation.

It is our goal to apply this to bleeding-edge innovation in alternate reality spaces.

```{r banner, echo=FALSE, out.width="100%", fig.cap="Official MAVRX Lab banner."}
library(linguisticsdown)
include_graphics2("images/CAST_Mixed-Augmented-Virtual-Extended-Reality-Lab_SCRIPT_TEMPLATE_2018_PRIMARY.png")
```


## Identity {-}

The lab's identity is determined by three basic concepts: its mission, vision, and values, but also of our dedication to praxis. Praxis as we refer to it can be defined as:

>the process by which a theory, lesson, or skill is enacted, embodied, or realized [and] the act of engaging, applying, exercising, realizing, or practicing ideas^[[Praxis (process)](https://en.wikipedia.org/wiki/Praxis_(process))].


## Mission {-}
The primary mission of the MA\{VR\}X Lab is to develop human-focused ideas through technology, transparency, and care, with a focus on extending our reality using technology and evidence-based methodology.

## Vision {-}
Manifested in the nexus of technology research, evidence-based pedagogy, and boundary-pushing ideas, the MA\{VR\}X Lab will act as a space for chances to be taken, brilliance to be realized, and people to come together.

## Values {-}
The MA\{VR\}X Lab’s vision is one of transparency, openness, and optimism. At all possible times, we believe knowledge should be not just presented publicly but developed there, as well. We are humans. We make mistakes and we want to make them in public so others may learn. We make those on our way to create great things and help build a better future for everyone.

## Code of Conduct {-}

In addition to the University of Arizona [Student Code of Conduct](https://deanofstudents.arizona.edu/student-rights-responsibilities/student-code-conduct), the MA\{VR\} X Lab would like to emphasize that it is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof). We do not tolerate harassment of lab members in any form. Sexual language and imagery is generally not appropriate for any lab venue, including lab meetings, presentations, or discussions.^[Adapted from [Lab Code of Conduct — DIB Lab 1.0 documentation](http://ivory.idyll.org/lab/coc.html).]