# Practices and Protocols {#protocols}

We deal with disparate technologies, fields, and methodologies. Having clear and available policies, practices, and protocols is absolutely essential.

## Documentation and Manuscripts {#docs-and-mans}

### File Formats {#fileformats}

Along with the \@ref(openness) we strive for when disseminating work via the lab, open formats should also be used when possible.

Documents: [markdown](https://www.markdownguide.org/cheat-sheet) ([Rmarkdown](https://uoepsy.github.io/usmr/cheatsheet/rmarkdown-2.0.pdf)) or RTF  
Audio: [FLAC - Free Lossless Audio Codec](https://xiph.org/flac/) or [OGG (Ogg Vorbis)](https://www.xiph.org/vorbis/)
Images: [JPEG-2000](https://jpeg.org/jpeg2000/index.html) or [TIFF](https://www.adobe.com/creativecloud/file-types/image/raster/tiff-file.html)  
Video: [MP4](https://en.wikipedia.org/wiki/MPEG-4_Part_14) or [MKV](https://en.wikipedia.org/wiki/Matroska) (H.264 or H.265 encoded)

While the University of Arizona provides free access to the entire Adobe Creative Cloud to anyone in its ecosystem, which the lab primarily uses, we also encourage the knowledge and use of free, open source software (FOSS) as an optional alternative:

+ [HandBrake: Open Source Video Transcoder](https://handbrake.fr/)
+ [GIMP - GNU Image Manipulation Program](https://www.gimp.org/)
+ [ardour - the digital audio workstation](https://ardour.org/)

### Documenting and Record Keeping {#documenting}

Projects should be housed in the lab's OSF project but the actual work done in these projects--writing, code, et cetera--should typically go in a GitHub repository within the lab's organization, especially student-driven projects. You may find that faculty-driven content may reside elsewhere but should still be linked within an OSF project. That repository can then be linked to the OSF sub-project. 

Having a well-written and organized `README` file in your repository is absolutely essential. To conform with [UA Research Data Repository Policies](https://data.library.arizona.edu/data-management/best-practices/data-documentation-readme-metadata) (and to have a consistent organization), you should at least start with the [README_template.txt](https://osf.io/sj8xv/) they provide. You are also encouraged to maintain a step-by-step process that describes your project environment, how to run any cleaning scripts (if applicable), and how to reproduce the manuscript/slide deck/et cetera. [software_in_research_survey_2014/README.md](https://github.com/softwaresaved/software_in_research_survey_2014/blob/1.0/README.md) is a good example of this.

Likewise, when describing commits in GitHub or describing updates in OSF, please don't skimp. Commits are cheap and the next person that reads what you left will thank you.

*Protip*: use GitHub's `Release` function to keep track of substantive updates to a project by keeping track of release notes and next steps. This will also help spin up a new collaborator should someone join your project.

Note that you don't just have to be coding applications to use GitHub! Use it for slide decks, papers, websites, and all sorts of things (like this lab manual, for example!).

### Filenames

We believe in standardizing as much as we can in order for consistency and clarity. Filenames should be chosen using the three considerations delimited by [Jenny Bryan's "How to name files"](https://speakerdeck.com/jennybc/how-to-name-files?slide=4). They should have the following qualities:

1. Machine readable
1. Human readable
1. Plays well with default ordering

## Lab Safety

...

## Reserving Lab Equipment

Reserving or checking out lab equipment should be done via our online lab inventory management system, [Bookkit by Clustermarket](https://www.clustermarket.com). This system is invite-only, so let the director know if you don't have access. Lab assistants, researchers, et cetera, are free to use lab equipment without reserving it, presuming they aren't precluding a reservation. Please keep in mind that lab equipment does need to be sterilized and recharged between uses and equipment that *is* checked out should be returned in the same fashion (with the exception of the rechargeable batteries; the lab will take care of those upon receipt).

## Requesting Lab Services

It's possible, also using Bookkit, for lab services to be requested by outside entities. Some services like 3D scanning of a property using a Matterport camera requires a certain amount of training. Other services, like providing assistance with software, can be done by those with the expertise necessary. Remember to let the director know if you have a particular skill that you'd like to offer as a service through the lab. (Know Unity? Perfect. Proficient with Adobe Aero? Awesome. These are great services to offer.)