# (APPENDIX) Appendix {-} 

# Step-by-Step Project Lifecycle

This is a step-by-step instruction on how to begin a project from scratch. This is, as the rest of the manual, a living document. Coincidentally, this same basic process can be used for class projects or papers by following just the relevant steps. The basic checklist goes like this:

1. Pitch your idea to the director (and, if you're a student researcher, your faculty research advisor) and do groundwork
1. Create your project in OSF
1. Create CRediT list of planned contributors and add them in the project
1. Submit for IRB approval with faculty research advisor (optional, depending on the type of study)
1. Pre-register (with sign-off from faculty research advisor)
1. Data Depositing

## Pitch Your Idea

This is actually two steps and, if related to a class project, is very straightforward:

1. Have an "elevator pitch," being able to describe what you want to study, why, and what you hypothesize you'll find in three sentences. Pitch this (to the director or, if you're a student researcher, to your faculty research advisor).
1. With initial approval of the concept, you need to then go on to provide the groundwork for the study: a literature review, research question(s), and so on. This creates the basis for the next stages like the IRB and pre-registration (remember, the IRB even requires a basic literature review and your study will absolutely need it, so best to begin early).

This is very likely exploratory at this stage and *that is just fine*. You may even flip back and forth between steps 1 and 2 as you delve deeper into the topic. Again, *perfectly normal* and expected. This is what research is all about.

## Create Your Project

+ [Create a Project from a Template – OSF Guides](https://help.osf.io/hc/en-us/articles/360019930093-Create-a-Project-from-a-Template#Use-a-public-project-as-a-template)

For consistency within the lab's organization, you'll be creating your project from a template. At this point, you'll want to pre-register your study. Remember, your *project* is a living, breathing thing that can be edited at will. *Registrations* are a little different, which we'll come to shortly.

You can also choose a description for your project at this point and a license. It's important to remember that data itself cannot be copyrighted but a database and the analysis of that data can. The [University of Arizona's Data Repository License Matrix](https://osf.io/f57nz/) provides a few suggestions (though these are specifically for data deposited in ReDATA, they're best practices):

1. Data: [Creative Commons — CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) (public domain; no copyright)
1. Documents & Media: [Creative Commons — Attribution 4.0 International — CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) 
1. Code/Software: [MIT License](https://choosealicense.com/licenses/mit/)

At this point, you'll also want to have watched the OSF tutorial videos to orient yourself to how the platform works and why we use it.

## CRediT List & Project Contributors

As mentioned in the [authoring](#authorship) section, you'll want to employ the CRediT taxonomy to transparently identify who is responsible for doing what within the lifecycle of your research study. If it's a solo study, your list may be very basic and simply identify your faculty research advisor or the director with "Supervision," leaving the rest blank and, by default, assigned to you. A more complex project will require more roles. These should be identified in good faith as they are planned; they are not contracts. Include this list, either as a spreadsheet or a link (to a Google Sheet, for example) in your project (if you used the lab's template, you'll already have this).

Make sure to include these folks in the *Contributors* list in your project.

## IRB Approval (optional, depending on project)

If your project, generally speaking, involves humans other than yourself (a meta-study, for example, or one using existing data does not require this), you will likely need to get approval from the Institutional Research Board (IRB) and have had done the required training through the Human Subjects Protection Program (HSPP). 

>University of Arizona students/residents who act as PIs are held to the same ethical and regulatory standards as faculty PIs. They are expected to follow all University policies and processes regarding human research.
>
>It is at the College and/or Department’s discretion whether a student or resident can serve as a PI. If a student (whether undergraduate or graduate) or a resident is serving as the PI, then a University advisor must be listed on the Verification of Human Subjects Training Form (VOTF) and have current training. The advisor does not need to be the student’s academic advisor or dissertation/thesis committee member, but must have an academic appointment at the University of Arizona. Advisors must sign off on the human research application and will be copied on all correspondence regarding the student’s human research project.^[[Conducting Human Subjects Research | UArizona Research, Innovation & Impact](https://research.arizona.edu/administration/getting-started/Principal-Investigator-Eligibility/conducting-human-subjects-research)]

One fringe benefit of needing to go through the IRB process is, having done this, your pre-registration content is almost entirely completed. Still, you'll need to get IRB approval *prior* to making your plan public.

## Pre-registration

Pre-registration is, more or less, a transparent plan of action and justification. See [OSF Registries | ADHD and Hyperfocus](https://osf.io/ta92r) for a good example of what this looks like. You don't *have* to have all the answers, all the exact specifics, but you should endeavor to provide the information you *do* have and explain why you can't or won't provide the others. Why pre-register, though?

>The main goal of preregistering one’s research is to make it easier for readers (and yourself) to distinguish between what the you set out to do (confirmation) and what was discovered along the way (exploration).^[[Preregistration: A Plan, Not a Prison](https://www.cos.io/blog/preregistration-plan-not-prison)]

It also has the benefit of establishing precisely what you intended and expect to find, precluding $p$-hacking^[[P-Hacking – Statistical Bullshit](https://statisticalbullshit.com/2017/07/17/p-hacking/)]. That said, remember that pre-registration is a *plan* and, as such, may become outdated or obsolete when things change unexpectedly. Preferably, if things do change, you should simply create a new pre-registration in the same project and either withdraw the previous one or simply reference the original now out-of-date pre-registration the new one. The time at which you do this is important^[[Preregistration: A Plan, Not a Prison](https://www.cos.io/blog/preregistration-plan-not-prison)].

Here's a very important aspect of registering a project:

>A registration on OSF creates a frozen, time-stamped version of a project that cannot be edited or deleted. The original project can still be edited, while the registered version cannot. You might create a registration to capture a snapshot of your project at certain points in time – such as right before data collection begins, when you submit a manuscript for peer review, or upon completion of a project.

Technically, you *can* update a pre-registration within a particular set of circumstances^[[Introduction to Updating – OSF Guides](https://help.osf.io/hc/en-us/articles/4414482864663-Introduction-to-Updating-)]. Presume that the research design you're planning on using is the one you *will* use. Registration updates are for situations outside the researcher's control that are necessary to the project's completion. The logistical changes necessitated by COVID-19 would be one example of this. You should also consider creating a pre-data-collection registration *and* a pre-data-analysis registration to capture any changes or alterations you'll be requiring prior to data analysis.

[How To Properly Preregister A Study - Data Colada](http://datacolada.org/64)

+ Choose the right pre-registration template: [Select a Registration Template – OSF Guides](https://help.osf.io/hc/en-us/articles/360019738794-Select-a-Registration-Template) (it is very likely you will choose one of the following)
  1. [OSF | Qualitative Preregistration Template.docx](https://osf.io/w4ac2/)
  1. [OSF | Preregistration for Qualitative Research Template.docx](https://osf.io/b6xmd/) (Kern & Skrede Gleditsch, 2017)
  1. [OSF | Pre-Registration in Social Psychology (van 't Veer & Giner-Sorolla, 2016) Pre-Registration.docx](https://osf.io/ce3hr/)
  1. [OSF | AsPredicted registration.docx](https://osf.io/fnsb6/)^[This is a good one to choose as it is very open and is what is included in the lab's project template. -RS]
  1. [OSF | Replication Recipe (Brandt et al., 2013) Pre-Registration.docx](https://osf.io/4jd46/)
    
It's understandable that undergraduate researchers, especially, may feel hesitant to pre-register their work given they're still learning not just the content they're researching but *how to* research. This is actually a great reason to go through the open science framework: that willingness to demonstrate growth, transparency, and a dedication to the process can be tremendously impressive.

## Depositing Data

Your collected data may be easy to handle, as in the case of a small pilot survey, or it may take up tremendous space, as in the case of videos of interviews, large metadata collections, scraping, et cetera. Using the [ReDATA](#redata) platform requires the inclusion of a [README](https://osf.io/sj8xv/) helps that data to be found. Of course, you should always follow legal requirements for what kinds of information can be made available (this will be spelled out very clearly in the IRB if you are dealing with personally identifiable data).

Regardless, check with your faculty research advisor or the director to see which platform/repository is most appropriate for your particular kind of data.